#!/usr/bin/env bash
set -euo pipefail

repo_root="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"

roles_dir="${repo_root}/.agents/roles"
claude_dir="${repo_root}/.claude/agents"
codex_dir="${repo_root}/.codex/agents"

check_only=false

if [[ "${1:-}" == "--check" ]]; then
  check_only=true
elif [[ -n "${1:-}" ]]; then
  echo "Usage: $0 [--check]" >&2
  exit 2
fi

if [[ ! -d "${roles_dir}" ]]; then
  echo "Error: missing ${roles_dir}" >&2
  exit 1
fi

mkdir -p "${claude_dir}" "${codex_dir}"

extract_frontmatter_value() {
  local file="$1"
  local key="$2"

  awk -v key="${key}" '
    BEGIN { in_frontmatter = 0 }

    NR == 1 && $0 == "---" {
      in_frontmatter = 1
      next
    }

    in_frontmatter && $0 == "---" {
      exit
    }

    in_frontmatter && $0 ~ ("^" key ":[[:space:]]*") {
      sub("^" key ":[[:space:]]*", "", $0)
      print
      exit
    }
  ' "${file}"
}

toml_escape() {
  local value="$1"

  value="${value//\\/\\\\}"
  value="${value//\"/\\\"}"

  printf '%s' "${value}"
}

render_codex_adapter() {
  local filename="$1"
  local name="$2"
  local description="$3"

  local escaped_name
  local escaped_description

  escaped_name="$(toml_escape "${name}")"
  escaped_description="$(toml_escape "${description}")"

  cat <<TOML
# Generated by scripts/sync-agents.sh.
# Canonical role: .agents/roles/${filename}
# Do not edit this file directly.

name = "${escaped_name}"
description = "${escaped_description}"

developer_instructions = """
開始任何工作前，必須先讀取並完整遵守：

- AGENTS.md
- .agents/roles/${filename}

\`.agents/roles/${filename}\` 是此 agent 的 canonical role definition。
其中的角色職責、工作流程、限制與輸出要求均適用。

若角色定義與 AGENTS.md 衝突，以 AGENTS.md 為準。
"""
TOML
}

has_error=false

for role_file in "${roles_dir}"/*.md; do
  [[ -e "${role_file}" ]] || continue

  filename="$(basename "${role_file}")"

  # README.md documents this directory; it is not a role definition.
  [[ "${filename}" == "README.md" ]] && continue

  slug="${filename%.md}"

  name="$(extract_frontmatter_value "${role_file}" "name")"
  description="$(extract_frontmatter_value "${role_file}" "description")"

  if [[ -z "${name}" ]]; then
    echo "Error: ${role_file} is missing frontmatter 'name'." >&2
    has_error=true
    continue
  fi

  if [[ -z "${description}" ]]; then
    echo "Error: ${role_file} is missing frontmatter 'description'." >&2
    has_error=true
    continue
  fi

  if [[ "${name}" != "${slug}" ]]; then
    echo "Error: role name '${name}' must match filename '${slug}'." >&2
    has_error=true
    continue
  fi

  # ----------------------------------------------------------
  # Claude symlink
  # ----------------------------------------------------------

  claude_link="${claude_dir}/${filename}"
  claude_target="../../.agents/roles/${filename}"

  if [[ "${check_only}" == true ]]; then
    if [[ ! -L "${claude_link}" ]]; then
      echo "DRIFT:  .claude/agents/${filename} is missing or not a symlink."
      has_error=true
    elif [[ "$(readlink "${claude_link}")" != "${claude_target}" ]]; then
      echo "DRIFT:  .claude/agents/${filename} points to the wrong target."
      has_error=true
    else
      echo "OK:     .claude/agents/${filename}"
    fi
  else
    if [[ -L "${claude_link}" ]]; then
      current_target="$(readlink "${claude_link}")"

      if [[ "${current_target}" == "${claude_target}" ]]; then
        echo "OK:     .claude/agents/${filename}"
      else
        rm "${claude_link}"
        ln -s "${claude_target}" "${claude_link}"
        echo "Linked: .claude/agents/${filename} -> ${claude_target}"
      fi
    elif [[ -e "${claude_link}" ]]; then
      echo "Skip:   .claude/agents/${filename} exists and is not a symlink."
    else
      ln -s "${claude_target}" "${claude_link}"
      echo "Linked: .claude/agents/${filename} -> ${claude_target}"
    fi
  fi

  # ----------------------------------------------------------
  # Codex adapter
  # ----------------------------------------------------------

  codex_file="${codex_dir}/${slug}.toml"
  expected_file="$(mktemp)"
  trap 'rm -f "${expected_file}"' EXIT

  render_codex_adapter \
    "${filename}" \
    "${name}" \
    "${description}" > "${expected_file}"

  if [[ "${check_only}" == true ]]; then
    if [[ ! -f "${codex_file}" ]]; then
      echo "DRIFT:  .codex/agents/${slug}.toml is missing."
      has_error=true
    elif ! cmp -s "${expected_file}" "${codex_file}"; then
      echo "DRIFT:  .codex/agents/${slug}.toml is out of date."
      has_error=true
    else
      echo "OK:     .codex/agents/${slug}.toml"
    fi
  else
    mv "${expected_file}" "${codex_file}"
    echo "Built:  .codex/agents/${slug}.toml"
  fi

  rm -f "${expected_file}"
  trap - EXIT
done

if [[ "${has_error}" == true ]]; then
  exit 1
fi

if [[ "${check_only}" == true ]]; then
  echo "Agent definitions are in sync."
fi
